version: '3.8'

services:
  db:
    image: postgres:16.3-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      # Primeira porta: Porta que será usada fora do container
      # Segunda porta: Porta que será usada dentro do container
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
